# Generated by Django 3.1.7 on 2022-01-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('reg_number', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=1)),
                ('unit_title', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
