# Generated by Django 3.1.7 on 2022-01-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reg_number', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('secret_key', models.CharField(max_length=20)),
                ('current_semester', models.CharField(max_length=1)),
                ('current_year', models.CharField(max_length=4)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
